#!/usr/bin/env bash
# STAR prompt_close SFT on single machine (4x4090).
set -euo pipefail

cd /root/work/R1SGG_STAR

export GPUS_PER_NODE="${GPUS_PER_NODE:-4}"
export WANDB_PROJECT="${WANDB_PROJECT:-RL4SGG}"
export TORCH_NCCL_ASYNC_ERROR_HANDLING=1
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
REPORT_TO="${REPORT_TO:-none}"

# Local 7B base model (downloaded beforehand).
MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH:-/root/shared-nvme/models/Qwen2-VL-7B-Instruct}"
# STAR HF DatasetDict generated by build_star_hf_dataset_with_images.py
DATASET_NAME="${DATASET_NAME:-/root/shared-nvme/datasets/STAR/star_r1sgg_hf}"
OUTPUT_DIR="${OUTPUT_DIR:-/root/shared-nvme/models/qwen2vl-7b-sft-star-close}"
RUN_NAME="${RUN_NAME:-Qwen2-VL-7B_star_sgg_close_sft}"
ATTN_IMPL="${ATTN_IMPL:-sdpa}"
MAX_OBJECTS="${MAX_OBJECTS:-160}"
MAX_RELATIONSHIPS="${MAX_RELATIONSHIPS:-600}"
# Leave empty/0 to disable explicit pixel cap in processor.
MAX_PIXELS="${MAX_PIXELS:-0}"
# Leave empty/0 to disable explicit pixel floor in processor.
MIN_PIXELS="${MIN_PIXELS:-0}"
# Keep token length bounded for 24GB cards.
MAX_TOKEN_LENGTH="${MAX_TOKEN_LENGTH:-3072}"
RANDOM_SUBGRAPH_SAMPLING="${RANDOM_SUBGRAPH_SAMPLING:-true}"
SUBGRAPH_SEED="${SUBGRAPH_SEED:-42}"
ADAPTIVE_IMAGE_RESIZE="${ADAPTIVE_IMAGE_RESIZE:-true}"
ADAPTIVE_RISK_MAX_PIXELS="${ADAPTIVE_RISK_MAX_PIXELS:-802816}"
ADAPTIVE_RISK_PIXELS_THRESHOLD="${ADAPTIVE_RISK_PIXELS_THRESHOLD:-12000000}"
ADAPTIVE_RISK_COMPLEXITY_THRESHOLD="${ADAPTIVE_RISK_COMPLEXITY_THRESHOLD:-500}"
ADAPTIVE_TILE_RISKY_SAMPLE="${ADAPTIVE_TILE_RISKY_SAMPLE:-true}"
FORCE_TILE_ALL_SAMPLES="${FORCE_TILE_ALL_SAMPLES:-false}"
ADAPTIVE_TILE_MAX_PIXELS="${ADAPTIVE_TILE_MAX_PIXELS:-802816}"
ADAPTIVE_TILE_OVERLAP_RATIO="${ADAPTIVE_TILE_OVERLAP_RATIO:-0.25}"
ADAPTIVE_TILE_MIN_OBJECTS="${ADAPTIVE_TILE_MIN_OBJECTS:-24}"
ADAPTIVE_TILE_MAX_TRIALS="${ADAPTIVE_TILE_MAX_TRIALS:-8}"
DDP_TIMEOUT="${DDP_TIMEOUT:-3600}"
USE_FSDP="${USE_FSDP:-true}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-8}"
DATALOADER_PIN_MEMORY="${DATALOADER_PIN_MEMORY:-false}"

# Full-tiling every sample is CPU-heavy. Avoid multi-worker stalls.
if [ "$FORCE_TILE_ALL_SAMPLES" = "true" ] && [ "$DATALOADER_NUM_WORKERS" != "0" ]; then
  echo "[INFO] FORCE_TILE_ALL_SAMPLES=true detected; overriding DATALOADER_NUM_WORKERS to 0"
  DATALOADER_NUM_WORKERS=0
fi

mkdir -p "$OUTPUT_DIR"

# When loading from a local model folder, force offline mode
# to avoid repeated HEAD retries to huggingface.co.
if [ -d "$MODEL_NAME_OR_PATH" ]; then
  export HF_HUB_OFFLINE=1
  export TRANSFORMERS_OFFLINE=1
fi

# 4 (GPUs) * 1 (per GPU) * 8 (grad accum) = global batch 32
EXTRA_PIXEL_ARGS=()
if [ "${MAX_PIXELS}" != "0" ] && [ -n "${MAX_PIXELS}" ]; then
  EXTRA_PIXEL_ARGS+=(--max_pixels "$MAX_PIXELS")
fi
if [ "${MIN_PIXELS}" != "0" ] && [ -n "${MIN_PIXELS}" ]; then
  EXTRA_PIXEL_ARGS+=(--min_pixels "$MIN_PIXELS")
fi
EXTRA_FSDP_ARGS=()
if [ "$USE_FSDP" = "true" ]; then
  EXTRA_FSDP_ARGS+=(--fsdp "full_shard auto_wrap" --fsdp_config local_scripts/fsdp_config.json)
fi

LAUNCHER=(/root/.conda/envs/r1sgg/bin/torchrun --nnodes 1 --nproc_per_node "$GPUS_PER_NODE" --node_rank 0)
if [ "$GPUS_PER_NODE" = "1" ] && [ "$USE_FSDP" = "false" ]; then
  LAUNCHER=(/root/.conda/envs/r1sgg/bin/python)
fi

"${LAUNCHER[@]}" \
  src/sft_sgg.py \
  --model_name_or_path "$MODEL_NAME_OR_PATH" \
  --dataset_name "$DATASET_NAME" \
  --learning_rate 1e-5 \
  --per_device_train_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --warmup_ratio 0.05 \
  --max_grad_norm 0.3 \
  --logging_steps 1 \
  --dataloader_num_workers "$DATALOADER_NUM_WORKERS" \
  --dataloader_pin_memory "$DATALOADER_PIN_MEMORY" \
  --bf16 true \
  --tf32 true \
  --report_to "$REPORT_TO" \
  --attn_implementation "$ATTN_IMPL" \
  --max_objects "$MAX_OBJECTS" \
  --max_relationships "$MAX_RELATIONSHIPS" \
  --max_token_length "$MAX_TOKEN_LENGTH" \
  --random_subgraph_sampling "$RANDOM_SUBGRAPH_SAMPLING" \
  --subgraph_seed "$SUBGRAPH_SEED" \
  --adaptive_image_resize "$ADAPTIVE_IMAGE_RESIZE" \
  --adaptive_risk_max_pixels "$ADAPTIVE_RISK_MAX_PIXELS" \
  --adaptive_risk_pixels_threshold "$ADAPTIVE_RISK_PIXELS_THRESHOLD" \
  --adaptive_risk_complexity_threshold "$ADAPTIVE_RISK_COMPLEXITY_THRESHOLD" \
  --adaptive_tile_risky_sample "$ADAPTIVE_TILE_RISKY_SAMPLE" \
  --force_tile_all_samples "$FORCE_TILE_ALL_SAMPLES" \
  --adaptive_tile_max_pixels "$ADAPTIVE_TILE_MAX_PIXELS" \
  --adaptive_tile_overlap_ratio "$ADAPTIVE_TILE_OVERLAP_RATIO" \
  --adaptive_tile_min_objects "$ADAPTIVE_TILE_MIN_OBJECTS" \
  --adaptive_tile_max_trials "$ADAPTIVE_TILE_MAX_TRIALS" \
  --ddp_timeout "$DDP_TIMEOUT" \
  "${EXTRA_PIXEL_ARGS[@]}" \
  --num_train_epochs 3 \
  --run_name "$RUN_NAME" \
  --save_steps 100 \
  --save_only_model true \
  --torch_dtype bfloat16 \
  "${EXTRA_FSDP_ARGS[@]}" \
  --use_predefined_cats true \
  --output_dir "$OUTPUT_DIR" \
  --seed 42
